services:
  api:
    build:
      context: .
      dockerfile: ./Api/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - backend-network
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=Users;User Id=sa;Password=YourStrong!Password;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
    ports:
      - "1433:1433"
    networks:
      - backend-network
    volumes:
      - db-data:/var/opt/mssql

networks:
  backend-network:
    driver: bridge

volumes:
  db-data:
